version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - mongodb-data:/data/db
    restart: always

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $ME_CONFIG_MONGODB_ADMINUSERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $ME_CONFIG_MONGODB_ADMINPASSWORD
      ME_CONFIG_MONGODB_URL: $ME_CONFIG_MONGODB_URL
      ME_CONFIG_BASICAUTH: $ME_CONFIG_BASICAUTH
    ports:
      - 8081:8081
    restart: always
    depends_on:
      - mongodb

volumes:
  mongodb-data: